# Generated by Django 4.0.1 on 2023-10-27 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_healthcaredetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcaredetails',
            name='fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_healthcare', to='api_app.patient'),
        ),
    ]
